version: "3"
services:
  web:
    image: ruby:2.7.1
    ports:
      - 5000:5000
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: Europe/Madrid
    volumes:
      - .:/web
      - ./.bundle:/usr/local/bundle
    working_dir: /web
    command: foreman start
