version: "3"
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - bundle:/bundle
    working_dir: /app
    command: bash -c "bundle install && heroku local"

  bundle:
    image: busybox
    volumes:
      - /bundle

volumes:
  bundle:
